# nginx-main.conf

# Set the process ID file location (Required for non-root user)
pid /var/run/nginx/nginx.pid;

# Nginx main context setup
user  nginx; # This is ignored due to the USER directive in Dockerfile, but is good practice
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Include our custom configuration file for the frontend app
    include /etc/nginx/conf.d/*.conf;
}
